# Generated by Django 5.2.9 on 2026-03-17 13:39

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0134_owner"),
        ("netbox_device_type_importer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaModuleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("vendor", models.CharField(max_length=50)),
                ("sha", models.CharField(max_length=40)),
                ("download_url", models.URLField(blank=True, null=True)),
                ("is_new", models.BooleanField(default=True)),
                ("imported_dt", models.IntegerField(blank=True, null=True)),
                ("is_imported", models.BooleanField(default=False)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Meta Module Types",
                "ordering": ("name", "vendor", "download_url"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
